# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "youtube"
    name       = "YouTube"
    weight     = -3
    url        = "https://www.youtube.com/@DanielComposes"

    [social.params]
        icon = "brand-youtube"

[[social]]
    identifier = "bluesky"
    name       = "Bluesky"
    weight     = -2
    url        = "https://bsky.app/profile/danieljordaan.com"

    [social.params]
        icon = "brand-bluesky"

[[social]]
    identifier = "twitter"
    name       = "Twitter"
    weight     = -1
    url        = "https://x.com/danielcomposes"

    [social.params]
        icon = "brand-twitter"

[[social]]
    identifier = "github"
    name       = "GitHub"
    weight     = 4
    url        = "https://github.com/danieljordaan"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "linktree"
    name       = "Linktree"
    weight     = 5
    url        = "https://linktr.ee/danieljordaan"

    [social.params]
        icon = "brand-linktree"
