# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post", "music", "games", "art"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    # since      = 2026
    # customText = ""

[dateFormat]
    published   = ":date_long"
    lastUpdated = ":date_long"

[sidebar]
    emoji    = "🎵"
    subtitle = "Composer and game developer"
    # avatar   = "img/avatar.png"

[article]
    headingAnchor = false
    math          = false
    toc           = false
    readingTime   = true

    [article.list]
        showTags = true

    [article.license]
        enabled = false
        default = ""

[widgets]
    homepage = [
        { type = "search" },
        { type = "taxonomy", params = { taxonomy = "music", icon = "music", showLink = true, title = "Music"}},
        { type = "taxonomy", params = { taxonomy = "games", icon = "keyboard", showLink = true, title = "Games"}},
        { type = "taxonomy", params = { taxonomy = "art", icon = "brush", showLink = true, title = "Art"}},
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = "danielcomposes"
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

[cookies]
    enabled      = false
    showSettings = true

    [cookies.categories]
        analytics  = true
        functional = true

## Comments
[comments]
    enabled  = false
    provider = "disqus"

    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.
